version: '2'
services:         
  openldap:    
    image: nursecurtis/docker-openldap:latest
    container_name: openldap                                                      
    env_file:
      - openldap.env
    tty: true
    stdin_open: true
    volumes:
      - $PWD/database:/var/lib/ldap/
      - $PWD/config:/etc/ldap/slapd.d/
      - $PWD/certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "" # important: same as hostname
    hostname: ""
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    env_file:
      - phpldap.env
    ports:
      - "18080:80"
    depends_on:
      - openldap
